# Generated by Django 5.2.8 on 2025-11-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=13, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('calorias', models.FloatField(verbose_name='Calorias (kcal)')),
                ('proteinas', models.FloatField(verbose_name='Proteínas (g)')),
                ('carboidratos', models.FloatField(verbose_name='Carboidratos (g)')),
                ('gorduras_totais', models.FloatField(verbose_name='Gorduras Totais (g)')),
                ('gorduras_saturadas', models.FloatField(verbose_name='Gorduras Saturadas (g)')),
                ('acucar_adicionado', models.FloatField(default=0, verbose_name='Açúcar Adicionado (g)')),
                ('acucar_total', models.FloatField(default=0, verbose_name='Açúcares totais (g)')),
                ('sodio', models.FloatField(verbose_name='Sódio (mg)')),
                ('fibras', models.FloatField(default=0, verbose_name='Fibras (g)')),
                ('contaminacao_cruzada', models.TextField(blank=True, null=True)),
                ('alergenicos', models.ManyToManyField(blank=True, to='core.alergenico')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('ingredientes', models.ManyToManyField(blank=True, to='core.ingrediente')),
            ],
        ),
    ]
