# Generated by Django 5.2.7 on 2025-12-02 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoContaminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aviso de contaminação cruzada',
                'verbose_name_plural': 'Avisos de contaminação cruzada',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AB', 'Aberto/Carrinho'), ('FI', 'Finalizado/Pago'), ('CA', 'Cancelado')], default='AB', max_length=2)),
                ('endereco_entrega', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=13, unique=True)),
                ('porcao', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('contaminacao_cruzada', models.TextField(blank=True, null=True, verbose_name='Texto livre de contaminação (opcional)')),
                ('calorias', models.FloatField(verbose_name='Calorias (kcal)')),
                ('proteinas', models.FloatField(verbose_name='Proteínas (g)')),
                ('carboidratos', models.FloatField(verbose_name='Carboidratos (g)')),
                ('gorduras_totais', models.FloatField(verbose_name='Gorduras Totais (g)')),
                ('acucar_total', models.FloatField(default=0, verbose_name='Açúcares totais (g)')),
                ('gorduras_saturadas', models.FloatField(verbose_name='Gorduras Saturadas (g)')),
                ('acucar_adicionado', models.FloatField(default=0, verbose_name='Açúcar Adicionado (g)')),
                ('sodio', models.FloatField(verbose_name='Sódio (mg)')),
                ('fibras', models.FloatField(default=0, verbose_name='Fibras (g)')),
                ('sem_gluten', models.BooleanField(default=False, verbose_name='Sem glúten')),
                ('sem_lactose', models.BooleanField(default=False, verbose_name='Sem lactose')),
                ('alto_teor_sodio', models.BooleanField(default=False, verbose_name='Alto em sódio')),
                ('alto_teor_acucar', models.BooleanField(default=False, verbose_name='Alto em açúcar')),
                ('alto_teor_gordura_sat', models.BooleanField(default=False, verbose_name='Alto em gordura saturada')),
                ('alergenicos', models.ManyToManyField(blank=True, to='core.alergenico')),
                ('avisos_contaminacao', models.ManyToManyField(blank=True, related_name='produtos', to='core.avisocontaminacao', verbose_name='Avisos de contaminação cruzada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('ingredientes', models.ManyToManyField(blank=True, to='core.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
