# Generated by Django 5.2.7 on 2025-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_itempedido_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='alto_teor_acucar',
            field=models.BooleanField(default=False, verbose_name='Alto em açúcar'),
        ),
        migrations.AddField(
            model_name='produto',
            name='alto_teor_gordura_sat',
            field=models.BooleanField(default=False, verbose_name='Alto em gordura saturada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='alto_teor_sodio',
            field=models.BooleanField(default=False, verbose_name='Alto em sódio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='porcao',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
