# Generated by Django 5.2.8 on 2025-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_alto_teor_acucar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avisos_contaminacao',
            field=models.ManyToManyField(blank=True, help_text="Selecione os alergênicos que aparecem apenas como risco de contaminação cruzada (ex.: 'pode conter glúten', 'pode conter leite').", related_name='produtos_contaminacao', to='core.alergenico', verbose_name='Avisos de Contaminação Cruzada'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='alergenicos',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='core.alergenico'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='contaminacao_cruzada',
            field=models.TextField(blank=True, null=True, verbose_name='Observação livre sobre contaminação (opcional)'),
        ),
    ]
