# Generated by Django 5.2.8 on 2025-12-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_avisos_contaminacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='avisos_contaminacao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='alergenicos',
            field=models.ManyToManyField(blank=True, to='core.alergenico'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='contaminacao_cruzada',
        ),
        migrations.AddField(
            model_name='produto',
            name='contaminacao_cruzada',
            field=models.ManyToManyField(blank=True, help_text='Selecione os alergênicos que podem estar presentes apenas por contaminação cruzada (traços).', related_name='produtos_contaminacao', to='core.alergenico', verbose_name='Alergênicos por contaminação cruzada'),
        ),
    ]
