# Generated by Django 5.2.8 on 2025-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produto_avisos_contaminacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='alergenicos',
            field=models.ManyToManyField(blank=True, related_name='produtos_alergenicos', to='core.alergenico'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='contaminacao_cruzada',
            field=models.ManyToManyField(blank=True, related_name='produtos_contaminacao', to='core.alergenico', verbose_name='Avisos de contaminação cruzada'),
        ),
    ]
