# Generated by Django 5.2.8 on 2025-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produto_alergenicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoContaminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aviso de contaminação cruzada',
                'verbose_name_plural': 'Avisos de contaminação cruzada',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='alergenicos',
            field=models.ManyToManyField(blank=True, to='core.alergenico'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='contaminacao_cruzada',
        ),
        migrations.AddField(
            model_name='produto',
            name='avisos_contaminacao',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='core.avisocontaminacao', verbose_name='Avisos de contaminação cruzada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='contaminacao_cruzada',
            field=models.TextField(blank=True, null=True, verbose_name='Texto livre de contaminação (opcional)'),
        ),
    ]
