# Generated by Django 5.2.7 on 2025-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_avisocontaminacao_alter_produto_alergenicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='acucar_total',
            field=models.FloatField(default=0, verbose_name='Açúcares totais (g)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sem_gluten',
            field=models.BooleanField(default=False, verbose_name='Sem glúten'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sem_lactose',
            field=models.BooleanField(default=False, verbose_name='Sem lactose'),
        ),
    ]
